#!/bin/bash

err() {
    echo "$@" 1>&2
}


curdir=`dirname "$0"`

if [ "$QT_QPA_PLATFORM" == "wayland-egl" ] ; then
    # Running under Wayland

    if [ -d "$curdir/qt5-install" ] ; then
        # We've been built from a pre-packaged Qt, which may not have included Wayland support

        if [ ! -f "$curdir/qt5-install/plugins/platforms/libwayland-egl.so" ] ; then
            err ""
            err "Running under Wayland, but this AppImage lacks the Qt Wayland backend. Forcing xcb backend instead."
            err "This warning should be harmless and not affect functionality."
            err ""
            err "Looked in '$curdir/qt5-install/plugins/platforms/libwayland-egl.so'"
            err ""

            export QT_QPA_PLATFORM=xcb
        fi
    fi
fi

if [ -x "$curdir/overte/interface/interface" ] ; then
    exec "$curdir/overte/interface/interface" "$@"
else
    err "Failed to find '$curdir/overte/interface/interface'! Broken AppImage?"
    exit 1
fi
